### ISSUE TITLE
Stepper examples might need delay

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_MotorKit#18]
These simple loops:
```python
for i in range(100):
    kit.stepper1.onestep()
```
might be running too fast.

See here:
https://forums.adafruit.com/viewtopic.php?f=24&t=154449&start=15#p762144

**Comment by ladyada** [comment]
kk wanna add a time.sleep(0.01) in there?

**Comment by caternuson** [comment]
Probably worth setting up and verifying the delay amount. I was just guessing at the `0.01` value and sounds like maybe it needed some tweaking. I could take a look, but don't think I currently have any of the PCA driven stepper HW. Only Crickit.

**Comment by ladyada** [comment]
any delay will work, i can do the commit

**Comment by dhalbert** [comment]
Fixed by #19.
