### ISSUE TITLE
Comment that `atexit` is only available in CPython.

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_MotorKit#23]
It is in two examples but only one warns that it is only for SBCs. This one doesn't: https://github.com/adafruit/Adafruit_CircuitPython_MotorKit/blob/4c872920d877baedef6aa7aee7bc7d4cf7436a22/examples/motorkit_robot.py#L13

**Comment by caternuson** [comment]
Fixed with #24
