### ISSUE TITLE
how to control the extra pwm pin ?

### ISSUE THREAD

**Issue by popoC** [adafruit/Adafruit_CircuitPython_MotorKit#39]
Can i using xtra pwm pin(0,1,14,15) to generate signal of the servo controler?

**Comment by popoC** [comment]
I found out that it can be modified directly,
kit._pca.channels[14].duty_cycle =  0xFFFF
Is there anything that needs attention in doing so?
Thanks for reply

**Comment by ladyada** [comment]
its ok
